_target_: src.models.kit_diffusion_module.DiffusionLitModule
diffusion_steps: 1000
beta_schedule: "squaredcos_cap_v2"
schedule_sampler: "uniform"
text_replace_prob: 0.2
lr: 0.0001
weight_decay: 0.0
ema_start: 100
ema_update: 10
ema_decay: 0.99
sampling_strategy: "ddpm"  # "ddpm" or "ddim"
epoch_sample_every: 10
sample_fps: 20
num_samples: 4
guidance_scale: 8.0

net:
  _target_: src.models.components.text2motion_model.Text2MotionUNet
  motion_length: 128
  in_channels: 147
  model_channels: 384
  out_channels: 294  # (2 * in_channels for variational inference)
  num_res_blocks: 2
  attention_resolutions: [2, 4, 8]
  dropout: 0.1
  channel_mult: [1, 1, 1, 1]
  conv_resample: True
  dims: 1
  num_classes: null
  use_checkpoint: False
  use_fp16: False
  num_heads: 6
  num_head_channels: -1
  num_heads_upsample: -1
  use_scale_shift_norm: True
  resblock_updown: True
  conv_kernel_size: 3
  conv_stride: 1
  conv_padding: 1
  conv_dilation: 1
  lm_hidden_size: 512
  max_text_length: 16
  pretrained_text_encoder_ckpt: null
