reference_motion_path: "[REFERENCE MOTION SAMPLE].json"
edit_joints_indices: [3,6,9,12,13,14,15,16,17,18,19,20,21,22,23]
edit_prompt: "a person is clapping."
use_reference_translation: true
use_smoothing: true
ckpt_path: "[CKPT PATH]"  
guidance_scale: 8.0


# JOINT IDX TABLE
# 00: Pelvis
# 01: L_Hip
# 02: R_Hip
# 03: Spine1
# 04: L_Knee
# 05: R_Knee
# 06: Spine2
# 07: L_Ankle
# 08: R_Ankle
# 09: Spine3
# 10: L_Foot
# 11: R_Foot
# 12: Neck
# 13: L_Collar
# 14: R_Collar
# 15: Head
# 16: L_Shoulder
# 17: R_Shoulder
# 18: L_Elbow
# 19: R_Elbow
# 20: L_Wrist
# 21: R_Wrist
# 22: L_Hand
# 23: R_Hand