# @package _global_

# specify here default evaluation configuration
defaults:
  - _self_
  - datamodule: humanml3d.yaml # choose the datamodule for evaluation
  - model: diffusion_hml3d.yaml
  - callbacks: null
  - logger: tensorboard.yaml
  - trainer: ddp.yaml
  - log_dir: evaluation.yaml

  - experiment: null

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

original_work_dir: ${hydra:runtime.cwd}

data_dir: ${original_work_dir}/data/

print_config: True

ignore_warnings: True

seed: null

name: "default"

# passing checkpoint path is necessary
ckpt_path: "[CKPT PATH]"
clip_ckpt: "[mCLIP MODEL PATH]"
guidance_scale: 8.0
