_target_: src.datamodules.babel_datamodule.BABELDataModule

data_dir: ${data_dir}
babel_setting: "L128_FPS20_O10"
batch_size: 32
num_workers: 16
pin_memory: False
split_setting: "final"  # one of a ["split", "final", "demo"]